version: '3.8'

services:
  web:
    build: .
    container_name: kshan_app
    restart: always
    ports:
      - "80:10000"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - PORT=10000
      - DJANGO_SETTINGS_MODULE=kshan_project.settings

