services:
  - type: web
    name: kshan-ai
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn kshan_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: kshan_project.settings
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: R2_ENABLED
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT_URL
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
