# Generated by Django 5.1.6 on 2026-08-29 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_batch", models.BooleanField(default=False)),
                ("batch_count", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PhotographerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "studio_name",
                    models.CharField(
                        blank=True, default="KSHAN Studio", max_length=255, null=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("instagram", models.CharField(blank=True, max_length=100, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                (
                    "studio_logo",
                    models.ImageField(blank=True, null=True, upload_to="logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("number_of_matches", models.IntegerField(default=0)),
                (
                    "anonymous_session_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("public", "Public QR"),
                    ("pin", "PIN Protected"),
                    ("face_only", "Face Search Only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="access_pin",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="cover_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="covered_events",
                to="gallery.photo",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("wedding", "Wedding"),
                    ("birthday", "Birthday"),
                    ("college", "College Event"),
                    ("corporate", "Corporate"),
                    ("sports", "Sports"),
                    ("festival", "Festival"),
                    ("conference", "Conference"),
                    ("school", "School Event"),
                    ("other", "Other"),
                ],
                default="wedding",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="photographer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="public_gallery_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("live", "LIVE"),
                    ("processing", "PROCESSING"),
                    ("draft", "DRAFT"),
                    ("ended", "ENDED"),
                ],
                default="live",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="is_highlight",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["event", "is_highlight"], name="gallery_pho_event_i_b3f7af_idx"
            ),
        ),
        migrations.AddField(
            model_name="downloadlog",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_logs",
                to="gallery.event",
            ),
        ),
        migrations.AddField(
            model_name="downloadlog",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="download_logs",
                to="gallery.photo",
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_logs",
                to="gallery.event",
            ),
        ),
    ]
