# Generated by Django 5.1.6 on 2026-08-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_downloadlog_photographerprofile_searchlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_client_proofing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="allow_favorites",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="download_permission",
            field=models.CharField(
                choices=[
                    ("original", "High-Res Originals & Batch ZIP"),
                    ("compressed", "Web Optimized Only"),
                    ("disabled", "View Only (Downloads Disabled)"),
                ],
                default="original",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="theme",
            field=models.CharField(
                choices=[
                    ("editorial", "Editorial Luxury"),
                    ("minimal", "Clean Minimal"),
                    ("cinema", "Cinematic Dark"),
                    ("wedding", "Warm Romantic"),
                    ("classic", "Classic Studio"),
                ],
                default="editorial",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="watermark_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="watermark_logo",
            field=models.ImageField(blank=True, null=True, upload_to="watermarks/"),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="watermark_opacity",
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="watermark_position",
            field=models.CharField(
                choices=[
                    ("center", "Center"),
                    ("bottom-right", "Bottom Right"),
                    ("bottom-left", "Bottom Left"),
                    ("tile", "Tiled Pattern"),
                ],
                default="bottom-right",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("public", "Open Event (Public QR)"),
                    ("pin", "PIN Protected"),
                    ("face_only", "Face Search Only"),
                    ("private", "Private Direct Link Only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("wedding", "Wedding"),
                    ("engagement", "Engagement"),
                    ("pre_wedding", "Pre-Wedding"),
                    ("birthday", "Birthday"),
                    ("college", "College Event"),
                    ("corporate", "Corporate"),
                    ("sports", "Sports"),
                    ("festival", "Festival"),
                    ("conference", "Conference"),
                    ("school", "School Event"),
                    ("other", "Other"),
                ],
                default="wedding",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Album Selection", max_length=255)),
                (
                    "access_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("target_count", models.IntegerField(default=80)),
                ("is_submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("client_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="gallery.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_selected", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gallery.collection",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="gallery.photo",
                    ),
                ),
            ],
            options={
                "unique_together": {("collection", "photo")},
            },
        ),
    ]
