# Generated by Django 5.1.6 on 2026-08-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_event_allow_client_proofing_event_allow_favorites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photographerprofile",
            name="booking_url",
            field=models.URLField(
                blank=True,
                help_text="Booking inquiry link or website",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="International format e.g. 919876543210",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GuestRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "anonymous_session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_registrations",
                        to="gallery.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="SubEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(db_index=True, max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_events",
                        to="gallery.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("event", "slug")},
            },
        ),
        migrations.AddField(
            model_name="photo",
            name="sub_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="gallery.subevent",
            ),
        ),
        migrations.CreateModel(
            name="GuestFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_session_id",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_favorites",
                        to="gallery.event",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_favorites",
                        to="gallery.photo",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("photo", "anonymous_session_id")},
            },
        ),
    ]
