# Generated by Django 5.1.6 on 2026-08-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_photographerprofile_booking_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_guest_download",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="allow_guest_upload",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("invite", "Invite Only"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="watermark_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="photo",
            name="exif_aperture",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="exif_camera",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="exif_date_taken",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="exif_exposure_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="exif_focal_length",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="exif_iso",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="exif_lens",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="uploaded_by_guest_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="uploaded_by_type",
            field=models.CharField(
                choices=[
                    ("official", "Official"),
                    ("guest", "Guest"),
                    ("team", "Team"),
                ],
                db_index=True,
                default="official",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cover_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="covered_albums",
                        to="gallery.photo",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="gallery.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlbumPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_photos",
                        to="gallery.album",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_albums",
                        to="gallery.photo",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "added_at"],
                "unique_together": {("album", "photo")},
            },
        ),
    ]
