# Generated by Django 5.1.6 on 2026-08-31 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gallery",
            "0005_event_allow_guest_download_event_allow_guest_upload_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price_full_event",
            field=models.IntegerField(
                default=0, help_text="Price in INR for full event photo bundle"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="price_per_photo",
            field=models.IntegerField(
                default=0, help_text="Price in INR for single photo download"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="pricing_model",
            field=models.CharField(
                choices=[
                    ("free", "Free Downloads"),
                    ("paid_per_photo", "Paid Per Photo"),
                    ("paid_full_event", "Paid Full Album Unlock"),
                ],
                default="free",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="event_credits",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="plan_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("starter", "Starter (Free)"),
                    ("pro_monthly", "Pro Monthly (₹1,499/mo)"),
                    ("studio_annual", "Studio Annual (₹12,999/yr)"),
                    ("event_pass", "Event Pass (₹499/event)"),
                ],
                default="starter",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True,
                        help_text="Razorpay Order ID (order_xxx)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Razorpay Payment ID (pay_xxx)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("signature", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("photographer_plan", "Photographer Subscription Plan"),
                            ("event_pass", "Photographer Event Pass"),
                            ("guest_photo_download", "Guest Single Photo Download"),
                            ("guest_event_unlock", "Guest Full Event Album Unlock"),
                            ("album_proofing_deposit", "Client Proofing Album Deposit"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid / Captured"),
                            ("failed", "Failed / Cancelled"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in INR", max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "guest_session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("guest_phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="JSON or descriptive notes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to="gallery.collection",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to="gallery.event",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to="gallery.photo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_session_id",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("is_full_event", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_purchases",
                        to="gallery.event",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_purchases",
                        to="gallery.photo",
                    ),
                ),
                (
                    "payment_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_purchases",
                        to="gallery.paymentorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "anonymous_session_id"],
                        name="gallery_gue_event_i_71a8f7_idx",
                    ),
                    models.Index(
                        fields=["photo", "anonymous_session_id"],
                        name="gallery_gue_photo_i_2106b6_idx",
                    ),
                ],
            },
        ),
    ]
