# Generated by Django 5.1.6 on 2026-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_event_price_full_event_event_price_per_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="price_full_event",
        ),
        migrations.AddField(
            model_name="event",
            name="google_drive_auto_sync",
            field=models.BooleanField(
                default=False, help_text="Enable automatic backup sync to Google Drive"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="google_drive_folder_url",
            field=models.URLField(
                blank=True,
                help_text="Google Drive folder link where event photos are synced/stored",
                max_length=500,
                null=True,
            ),
        ),
    ]
