# Generated by Django 5.1.6 on 2026-08-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_remove_event_price_full_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price_full_event",
            field=models.IntegerField(
                default=0, help_text="Price in INR for full event photo bundle"
            ),
        ),
    ]
