# Generated by Django 5.1.6 on 2026-08-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0008_event_price_full_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="storage_destination",
            field=models.CharField(
                choices=[
                    ("cloudflare", "Cloudflare R2 / Server Storage"),
                    ("google_drive", "Google Drive Cloud Storage"),
                    ("both", "Both (Cloudflare R2 & Google Drive Backup)"),
                ],
                default="cloudflare",
                help_text="Where uploaded event photos should be routed and stored",
                max_length=30,
            ),
        ),
    ]
