# Generated by Django 5.1.6 on 2026-09-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0009_event_storage_destination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="google_drive_auto_sync",
        ),
        migrations.RemoveField(
            model_name="event",
            name="google_drive_folder_url",
        ),
        migrations.RemoveField(
            model_name="event",
            name="storage_destination",
        ),
    ]
