# Generated by Django 5.1.6 on 2026-09-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0010_remove_event_google_drive_auto_sync_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppOTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=30)),
                ("otp_code", models.CharField(max_length=10)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Studio Passwordless Login"),
                            ("signup", "Studio Registration"),
                            ("guest_register", "Guest Verification"),
                        ],
                        default="login",
                        max_length=30,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
