# Generated by Django 5.1.6 on 2026-09-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0011_whatsappotpverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_watermark_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Always watermark site logo on bottom-right of photos",
                    ),
                ),
                (
                    "site_watermark_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="system/watermarks/"
                    ),
                ),
                ("site_watermark_opacity", models.FloatField(default=0.85)),
                ("site_brand_name", models.CharField(default="KSHAN", max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
