import { useState } from "react";

type Nav = { navigate: (screen: string) => void };
const images = [
  "https://images.unsplash.com/photo-1764286954620-28029fbae9b6?w=900&fit=crop",
  "https://images.unsplash.com/photo-1633104502699-b2ecf0fee294?w=900&fit=crop",
  "https://images.unsplash.com/photo-1600685912448-8bc35c141e18?w=900&fit=crop",
  "https://images.unsplash.com/photo-1714972383570-44ddc9738355?w=900&fit=crop",
  "https://images.unsplash.com/photo-1610173827002-62c0f1f05d04?w=900&fit=crop",
  "https://images.unsplash.com/photo-1648154164366-d067faecdc51?w=900&fit=crop",
  "https://images.unsplash.com/photo-1482575832494-771f74bf6857?w=900&fit=crop",
  "https://images.unsplash.com/photo-1735052709798-2abcc8c0d6e1?w=900&fit=crop",
];

function Brand() { return <span className="brand-lockup"><span className="brand-mark">✦</span>KSHAN</span>; }
function GuestLayout({ children, navigate }: Nav & { children: React.ReactNode }) { return <div className="guest-shell"><nav className="guest-nav"><button className="nav-link" onClick={() => navigate("home")}><Brand /></button><div className="nav-links"><button className="nav-link" onClick={() => navigate("event-gallery")}>Explore gallery</button><button className="btn btn-secondary" onClick={() => navigate("find-event")}>Find my photos <span>→</span></button></div></nav>{children}<footer className="guest-footer">KSHAN · Private, delightful photo delivery for every celebration.</footer></div>; }
function Home({ navigate }: Nav) { return <GuestLayout navigate={navigate}><main className="hero"><div><div className="eyebrow">The new ritual of event photography</div><h1 className="display">Every face.<br />Every <em>memory.</em></h1><p className="lede">KSHAN turns one simple selfie into a beautiful, private gallery of every moment you are part of.</p><div className="hero-actions"><button className="btn btn-primary" onClick={() => navigate("find-event")}>Find my photos <span>→</span></button><button className="btn btn-secondary" onClick={() => navigate("event-landing")}>See how it works</button></div><div className="hero-stats">{[["10k+","celebrations"],["2m+","memories delivered"],["98%","match accuracy"]].map(([v,l]) => <div key={l}><div className="stat-number">{v}</div><div className="stat-label">{l}</div></div>)}</div></div><div className="hero-art"><div className="hero-orbit"/><div className="hero-photo hero-photo-main"><img src={images[0]} /></div><div className="hero-photo hero-photo-left"><img src={images[2]} /></div><div className="hero-photo hero-photo-right"><img src={images[3]} /></div><div className="floating-chip"><span>✦</span><div><b>Your moments await</b><span>One selfie. Instant gallery.</span></div></div></div></main><section className="section"><div className="section-header"><div><div className="eyebrow">Simple by design</div><h2 className="section-title">Made for guests,<br />loved by photographers.</h2></div><p className="page-copy">Nothing to install, remember, or wait for. Just a beautiful path back to the moments that belong to you.</p></div><div className="step-grid">{[["01","Open your event","Scan the QR code or enter the code shared by your photographer."],["02","Take one selfie","A quick private selfie securely identifies your moments."],["03","Keep every memory","Browse, favourite, and download your photos in seconds."]].map(([n,t,d])=><article className="lux-card step-card" key={n}><div className="step-no">{n}</div><h3 className="card-title">{t}</h3><p className="card-copy">{d}</p></article>)}</div></section></GuestLayout>; }
function SamaroHome({ navigate }: Nav) { return <GuestLayout navigate={navigate}><main><section className="samaro-hero"><div className="proof"><span className="proof-avatars">{images.slice(1,4).map(x=><img src={x} key={x}/>)}</span>Loved by 2 million+ celebration guests</div><h1 className="samaro-title">AI photo sharing for<strong>every celebration.</strong></h1><p className="samaro-copy">From intimate weddings to large-scale events, KSHAN brings every photograph, guest, and beautiful moment into one effortless experience.</p><div className="samaro-actions"><button className="btn btn-primary" onClick={()=>navigate("find-event")}>Find my photos <span>→</span></button><button className="btn btn-secondary" onClick={()=>navigate("event-landing")}>See a live gallery</button></div><div className="product-window"><img src={images[0]}/><div className="window-copy"><div className="eyebrow">KSHAN CLOUD GALLERY</div><h2>One selfie. Every memory.</h2><p>A private, beautiful event gallery that lets every guest discover the photographs made for them.</p></div></div></section><section className="solution-strip"><h2>One KSHAN. Many joyful moments.</h2><div className="solution-tabs">{[["◈","Event photographers","Deliver galleries guests will never forget."],["◎","Wedding planners","Keep every celebration detail beautifully in sync."],["↗","Individual hosts","Invite everyone into the story in seconds."],["✦","Organisations","Give large events a personal, polished feel."]].map(([i,t,d])=><button className="solution-tab" key={t}><i>{i}</i><b>{t}</b><span>{d}</span></button>)}</div></section><section className="big-stats">{[["55k+","events created"],["200m+","media delivered"],["2m+","guests hosted"],["4k+","studios onboarded"]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</section><section className="feature-split"><div className="feature-visual"><img src={images[5]}/></div><div><div className="eyebrow">Private photo sharing, made simple</div><h2 className="section-title">A beautiful gallery for every guest.</h2><p className="page-copy" style={{marginTop:12}}>No apps, no passwords, and no time spent hunting through hundreds of photographs. KSHAN makes the delivery feel as special as the event.</p><div className="feature-points">{[["✓","Face discovery","Guests instantly find the photographs they are in."],["✓","Original quality","Keep every memory just as your photographer captured it."],["✓","Sharing controls","Give hosts complete control over every gallery."]].map(([i,t,d])=><div className="feature-point" key={t}><i>{i}</i><div><b>{t}</b><span>{d}</span></div></div>)}</div><button className="btn btn-primary" style={{marginTop:26}} onClick={()=>navigate("event-landing")}>Explore guest experience →</button></div></section></main></GuestLayout>; }
function FindEvent({ navigate }: Nav) { const [code,setCode]=useState(""); return <GuestLayout navigate={navigate}><main className="guest-page"><div className="search-card lux-card"><div className="eyebrow">Welcome to KSHAN</div><h1 className="page-title">Find your celebration</h1><p className="page-copy">Enter the event code from your invitation or QR standee.</p><input className="code-input" value={code} maxLength={8} placeholder="RP2026" onChange={e=>setCode(e.target.value.toUpperCase())}/><button className="btn btn-primary" style={{width:"100%"}} onClick={()=>navigate("event-landing")}>Continue to event <span>→</span></button><p className="card-copy" style={{marginTop:18}}>Your event code keeps every gallery private and personal.</p></div></main></GuestLayout>; }
function EventLanding({ navigate }: Nav) { return <GuestLayout navigate={navigate}><main className="guest-page"><section className="event-hero"><img src={images[1]}/><div className="event-hero-content"><div className="eyebrow">Rahul & Priya invite you</div><h1 className="display" style={{fontSize:"clamp(42px,5vw,66px)"}}>A celebration<br />of <em>forever.</em></h1><p className="lede">Find every beautiful moment you shared at Rahul & Priya's wedding.</p><div className="event-meta"><span className="tag">24 AUG 2026</span><span className="tag">THE LEELA, GOA</span><span className="tag">2,438 PHOTOS</span></div><div className="hero-actions"><button className="btn btn-primary" onClick={()=>navigate("selfie-capture")}>Find my photos <span>→</span></button></div></div></section><div className="feature-grid" style={{marginTop:16}}>{[["◈","Private by default","Your selfie is used only to find your moments."],["↓","Full-quality downloads","Keep your favourites in original quality."],["♡","Save what matters","Build a collection from every candid."],["✦","Instantly available","New photographs appear as the day unfolds."]].map(([i,t,d])=><div className="lux-card feature-card" key={t}><div style={{color:"var(--gold)",fontSize:20}}>{i}</div><h3 className="card-title" style={{fontSize:19}}>{t}</h3><p className="card-copy">{d}</p></div>)}</div></main></GuestLayout>; }
function Selfie({ navigate, confirm=false }: Nav & { confirm?: boolean }) { return <GuestLayout navigate={navigate}><main className="guest-page"><div className="selfie-layout"><section className="camera-stage"><div className="face-ring"><span>{confirm ? "✓" : "◎"}</span></div></section><aside className="info-stack"><div className="lux-card panel"><div className="eyebrow">{confirm ? "Looking good" : "Step 1 of 2"}</div><h1 className="page-title">{confirm ? "Ready to find your moments?" : "Let's find you in the story."}</h1><p className="page-copy">{confirm ? "We'll search the celebration and prepare your personal gallery." : "Use a clear, front-facing selfie. It will be deleted after the search."}</p><button className="btn btn-primary" style={{width:"100%",marginTop:22}} onClick={()=>navigate(confirm ? "searching" : "selfie-confirm")}>{confirm ? "Find my photos" : "Use this selfie"} <span>→</span></button><button className="btn btn-secondary" style={{width:"100%",marginTop:9}} onClick={()=>navigate("event-landing")}>Try another photo</button></div><div className="lux-card panel"><div className="eyebrow">Private & secure</div><p className="card-copy" style={{marginTop:10}}>Your face data is only used to match you with this event's photos. We never sell or reuse it.</p></div></aside></div></main></GuestLayout>; }
function Searching({ navigate }: Nav) { return <GuestLayout navigate={navigate}><main className="guest-page"><div className="search-card lux-card"><div className="face-ring" style={{width:150,margin:"12px auto 35px"}}><span>✦</span></div><div className="eyebrow">KSHAN AI AT WORK</div><h1 className="page-title">Gathering your moments</h1><p className="page-copy">Searching across 2,438 celebration photographs.</p><div className="progress-line" style={{margin:"28px 0 10px"}}><span style={{width:"72%"}}/></div><p className="card-copy">72% complete · This only takes a few seconds.</p><button className="btn btn-secondary" style={{marginTop:24}} onClick={()=>navigate("results")}>View results demo</button></div></main></GuestLayout>; }
function Gallery({ navigate, selection=false, all=false }: Nav & { selection?:boolean;all?:boolean }) { const [chosen,setChosen]=useState<number[]>(selection?[0,2]:[]); const toggle=(i:number)=>setChosen(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i]); return <GuestLayout navigate={navigate}><main className="guest-page"><div className="eyebrow">{all?"Rahul & Priya · event gallery":"Your private collection"}</div><h1 className="page-title">{all?"A day worth remembering":"We found 37 moments of you."}</h1><p className="page-copy">{all?"Browse the official celebration gallery.":"Tap a photo to view it, or select your favourites to download together."}</p><div className="gallery-toolbar"><div className="filter-tabs">{["All photos","Portraits","Candid","Dance floor"].map((f,i)=><button className={'filter-tab '+(!i?'active':'')} key={f}>{f}</button>)}</div>{selection?<button className="btn btn-primary" onClick={()=>navigate("photo-viewer")}>Download {chosen.length} photos</button>:<button className="btn btn-secondary" onClick={()=>navigate("photo-selection")}>Select favourites</button>}</div><div className="gallery-grid">{[...Array(20)].map((_,i)=><button className={'media-card '+(chosen.includes(i)?'selected':'')} key={i} onClick={()=>selection?toggle(i):navigate("photo-viewer")}><img src={images[i%images.length]} style={{height:i%3===0?250:i%3===1?190:310}}/>{selection&&chosen.includes(i)&&<span className="check">✓</span>}</button>)}</div></main></GuestLayout>; }
function Viewer({ navigate }: Nav) { return <div className="lightbox"><div className="lightbox-frame"><img src={images[0]}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"12px 4px 2px"}}><button className="btn btn-secondary" onClick={()=>navigate("results")}>← Back to gallery</button><div style={{display:"flex",gap:8}}><button className="btn btn-secondary">♡ Save</button><button className="btn btn-primary">Download ↓</button></div></div></div></div>; }
function NoResults({ navigate }: Nav) { return <GuestLayout navigate={navigate}><main className="guest-page"><div className="search-card lux-card"><div style={{fontSize:50,color:"var(--gold)"}}>⌁</div><h1 className="page-title">Your moments are still arriving.</h1><p className="page-copy">We couldn't find a confident match just yet. Your photographer may still be uploading the celebration.</p><div className="hero-actions" style={{justifyContent:"center"}}><button className="btn btn-primary" onClick={()=>navigate("selfie-capture")}>Try another selfie</button><button className="btn btn-secondary" onClick={()=>navigate("event-gallery")}>Browse event gallery</button></div></div></main></GuestLayout>; }
const screens:Record<string,React.ComponentType<Nav>>={home:Home,"find-event":FindEvent,"event-landing":EventLanding,"selfie-capture":p=><Selfie {...p}/>,"selfie-confirm":p=><Selfie {...p} confirm/>,searching:Searching,results:p=><Gallery {...p}/>,"photo-selection":p=><Gallery {...p} selection/>,"photo-viewer":Viewer,"no-results":NoResults,"event-gallery":p=><Gallery {...p} all/>};
export default function GuestScreens({screen,navigate}:{screen:string;navigate:(screen:string)=>void}){const Screen=screens[screen]??Home;return <Screen navigate={navigate}/>;}
